# Doc: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node for NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm ci
        
      - name: Publish Package to NPM
        run: npm publish -provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Setup Node for GPR
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Publish Package to GPR
        run: npm publish -provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
