# Doc: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Publish Package
        run: npm publish -provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
